name: mod_harbour.v2 for Windows 64

on:
  push:
    paths: 
      - '.github/workflows/mod_harbour.v2_win64.yml'

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Checkout harbour/core repo
        uses: actions/checkout@v2
        with:
          repository: harbour/core
          path: harbour
  
      - name: Updating Harbour hbssl for new OpenSSL 
        run: |
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'libeay32','libcrypto-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'ssleay32','libssl-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'libeay32','libcrypto-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'ssleay32','libssl-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc
         
      - name: Download and extract Harbour/Apache24 binaries
        shell: cmd      
        run: |
          curl -OL https://raw.githubusercontent.com/diegofazio/harbour_binaries/master/Windows/harbour_windows_64.zip
          7z x -y harbour_windows_64.zip -oharbour
          curl -OL https://raw.githubusercontent.com/diegofazio/harbour_binaries/master/apache24/win64.zip
          7z x -y win64.zip -oc:\Apache24

      - name: Checkout mod_harbour.v2 repo
        uses: actions/checkout@v2
        with:
          repository: mod-harbour/mod_harbour.v2
          ref: 'v2.0'
          path: harbour/contrib/mod_harbour.v2

      - name: Build mod_harbour.v2
        working-directory: harbour/contrib/mod_harbour.v2
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          ..\..\bin\win\msvc64\hbmk2 mod_harbour.v2.hbp -Lc:\Apache24\lib -Ic:\Apache24\include -ic:\Apache24\include

      - name: Prepare artifact
        shell: cmd
        run: |
          mkdir artifact
          mkdir artifact\Samples
          xcopy harbour\contrib\mod_harbour.v2\Samples\*.* .\artifact\Samples /E /H /C /I
          xcopy harbour\contrib\mod_harbour.v2\output\win64\mod_harbour.v2.so .\artifact /E /H /C /I

      - name: Upload mod_harbour.v2.so/libmhapache.dll/Samples to artifact
        uses: actions/upload-artifact@v2
        with:
          name: mod_harbour.v2_win64
          path: artifact
